# Generated by Django 5.1.1 on 2024-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image.png', upload_to='products/'),
        ),
    ]
