# Generated by Django 5.1.1 on 2024-10-09 14:23

import fruits_web.apps.platforms.models_container.product
import fruits_web.apps.platforms.models_container.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image.png', upload_to=fruits_web.apps.platforms.models_container.product.random_image_filename),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image.png', upload_to='', verbose_name=fruits_web.apps.platforms.models_container.user.random_image_filename),
        ),
    ]
