# Generated by Django 5.1.1 on 2024-10-18 07:37

import fruits_web.apps.platforms.models_container.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_alter_product_image_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image.png', upload_to=fruits_web.apps.platforms.models_container.user.random_image_filename),
        ),
    ]
